# CIITM Frontend - Project Funding Information
# Support this project and help us build the best institute website in India!
# Buy Me a Coffee: https://www.buymeacoffee.com/abhishek96z

buy_me_a_coffee: abhishek96z
