name: 🐛 Bug Report
description: Report an issue to help improve the project
title: "[BUG]: "
labels: ["bug", "triage", "needs verification" , "high priority"]
assignees:
  - abhishek-nexgen-dev
body:
  - type: markdown
    attributes:
      value: |
        # 🔍 Bug Report
        
        Thanks for taking the time to fill out this bug report! The more information you provide, the faster we can resolve the issue.
        
        Before submitting, please check if a similar issue already exists.
  
  - type: input
    id: contact
    attributes:
      label: 📧 Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: email@example.com or Discord username
    validations:
      required: false
  
  - type: textarea
    id: what-happened
    attributes:
      label: 🐞 What happened?
      description: Describe the bug in detail. What went wrong? What did you expect to happen instead?
      placeholder: When I clicked on X, I expected Y to happen but Z occurred instead...
      value: ""
    validations:
      required: true
  
  - type: textarea
    id: reproduction-steps
    attributes:
      label: 📋 Steps to Reproduce
      description: Provide detailed steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  
  
  - type: dropdown
    id: browsers
    attributes:
      label: 🌐 Browsers
      description: Which browsers are you experiencing the problem on?
      multiple: true
      options:
        - Chrome
        - Firefox
        - Safari
        - Edge
        - Opera
        - Brave
        - Samsung Internet
        - Other (please specify in description)
  
  - type: dropdown
    id: os
    attributes:
      label: 💻 Operating System
      description: Which operating system are you using?
      multiple: true
      options:
        - Windows
        - macOS
        - Linux
        - iOS
        - Android
        - Other (please specify in description)
    validations:
      required: true
  
  

  - type: textarea
    id: logs
    attributes:
      label: 📜 Relevant Logs
      description: Please copy and paste any relevant log output or error messages.
      render: shell
  
  - type: textarea
    id: screenshots
    attributes:
      label: 📸 Screenshots or Videos
      description: If applicable, add screenshots or videos to help explain your problem
      placeholder: Drag and drop images or video links here
  
  - type: checkboxes
    id: community
    attributes:
      label: 🤝 Community
      options:
        - label: I have joined the [Discord community](https://discord.com/invite/pZH3NymxtA) for real-time updates and support
        - label: I've searched for similar bugs before filing this issue
          required: true
        - label: I've included all the information needed to reproduce this bug
  
  - type: checkboxes
    id: terms
    attributes:
      label: 📜 Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/NexGenStudioDev/ciitm-frontend/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true